const api = {
    "comics" : [],
    "genre"  : [
        { name: "Tất cả"},{ name: "Action"},{ name: "Adult"},{ name: "Adventure"},{ name: "Big Brain"},{ name: "Chuyển Sinh"},{ name: "Comedy"},
        { name: "Comic"},{ name: "Cooking"},{ name: "Cổ Đại"},{ name: "Doujinshi"},{ name: "Drama"},{ name: "Ecchi"},{ name: "Fantasy"},{ name: "Family"},
        { name: "Harem"},{ name: "Historical"},{ name: "Horror"},{ name: "Josei"},{ name: "Live action"},{ name: "Manga"},{ name: "Manhua"},
        { name: "Manhwa"},{ name: "Martial Arts"},{ name: "Mature"},{ name: "Mecha"},{ name: "Mystery"},{ name: "Ngôn Tình"},{ name: "One shot"},
        { name: "Psychological"},{ name: "Romance"},{ name: "School Life"},{ name: "Sci-fi"},{ name: "Seinen"},{ name: "Shoujo"},{ name: "Shoujo Ai"},
        { name: "Shounen"},{ name: "Shounen Ai"},{ name: "Slice of Life"},{ name: "Smut"},{ name: "Soft Yaoi"},{ name: "Soft Yuri"},{ name: "Sports"},
        { name: "Supernatural"},{ name: "Tragedy"},{ name: "Trinh Thám"},{ name: "Truyện scan"},{ name: "Truyện Màu"},{ name: "Webtoon"},
        { name: "Xuyên Không"},{ name: "Hệ thống"}
    ]
}
let websiteComic = [
        // Danh sach website truyen chu-------------------------------------
    {linkComic: 'https://comics24hmoi.com/', 
        nameWebsite: 'comics24h', genreWebsite: "truyenchu"},
    {linkComic: 'https://congtruyen.org', 
        nameWebsite: 'congtruyen', genreWebsite: "truyenchu"},
    {linkComic: 'https://sstruyen.vn/', 
        nameWebsite: 'sstruyen', genreWebsite: "truyenchu"},
    {linkComic: 'https://truyenfull.vn/', 
        nameWebsite: 'truyenfull', genreWebsite: "truyenchu"},
    {linkComic: 'https://trumtruyen.vn/', 
        nameWebsite: 'trumtruyen', genreWebsite: "truyenchu"},
    {linkComic: 'https://thichtruyen.vn/', 
        nameWebsite: 'thichtruyen', genreWebsite: "truyenchu"},
    {linkComic: 'https://truyenchu.vn/', 
        nameWebsite: 'truyenchu', genreWebsite: "truyenchu"},
    {linkComic: 'https://truyenyy.pro/', 
        nameWebsite: 'truyenyy', genreWebsite: "truyenchu"},
        // Danh sach website truyen tranh-----------------------------------
    {linkComic: 'https://truyenqqvn.com', 
        nameWebsite: 'truyenqq', genreWebsite: "truyentranh"},
    {linkComic: 'https://www.a3manga.store/', 
        nameWebsite: 'a3manga', genreWebsite: "truyentranh"},
    {linkComic: 'https://www.nettruyenss.com', 
        nameWebsite: 'nettruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://baotangtruyen8.com', 
        nameWebsite: 'baotangtruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://thichdoctruyen.vip', 
        nameWebsite: 'thichdoctruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://wattpad.vn/', 
        nameWebsite: 'wattpad', genreWebsite: "truyentranh"},
    {linkComic: 'https://goctruyentranhvui1.com', 
        nameWebsite: 'goctruyentranh', genreWebsite: "truyentranh"},
    {linkComic: 'https://manga.io.vn', 
        nameWebsite: 'manga.io', genreWebsite: "truyentranh"},
    {linkComic: 'https://timtruyen3ss.com/', 
        nameWebsite: 'timtruyen3s', genreWebsite: "truyentranh"},
    {linkComic: 'https://blogtruyenmoi.com/', 
        nameWebsite: 'blogtruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://www.tamtruyen.com/',
        nameWebsite: 'tamtruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://nhattruyenbing.com/',
        nameWebsite: 'nhattruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://truyentranh18.vn/',
        nameWebsite: 'truyentranh18', genreWebsite: "truyentranh"},
    {linkComic: 'https://truyenbest.com/',
        nameWebsite: 'truyenbest', genreWebsite: "truyentranh"},
    {linkComic: 'https://acomicshot.com/',
        nameWebsite: 'acomics', genreWebsite: "truyentranh"},
    {linkComic: 'https://abtruyen.com/',
        nameWebsite: 'abtruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://tctruyen.com/',
        nameWebsite: 'tctruyen', genreWebsite: "truyentranh"},
    {linkComic: 'https://manhuavn.top/',
        nameWebsite: 'manhuavn', genreWebsite: "truyentranh"},
    {linkComic: 'https://tuoitho.mobi/',
        nameWebsite: 'tuoitho', genreWebsite: "truyentranh"},
    {linkComic: 'http://truyendoc.info/',
        nameWebsite: 'truyendoc', genreWebsite: "truyentranh"},
    {linkComic: 'https://doctruyentranh.net.vn/',
        nameWebsite: 'doctruyentranh', genreWebsite: "truyentranh"},
    {linkComic: 'http://alotruyentranh.com/',
        nameWebsite: 'alotruyentranh', genreWebsite: "truyentranh"},
    // Danh sach website truyen tranh18-----------------------------------
    {linkComic: 'https://truyenvn.fun/',
        nameWebsite: 'truyenvn', genreWebsite: "truyentranh18"},
    {linkComic: 'https://truyen18.xyz/',
        nameWebsite: 'truyen18.xyz', genreWebsite: "truyentranh18"},  
    {linkComic: 'https://damconuong.net/',
        nameWebsite: 'damconuong', genreWebsite: "truyentranh18"},
    {linkComic: 'https://doctruyen3qc.com/',
        nameWebsite: 'doctruyen3q', genreWebsite: "truyentranh18"},
    {linkComic: 'https://truyentranhs.com/',
        nameWebsite: 'truyentranhs.com', genreWebsite: "truyentranh18"},
    {linkComic: 'https://truyengihotqua.com/',
        nameWebsite: 'truyengihot', genreWebsite: "truyentranh18"},
    {linkComic: 'https://hentai24h.tv/',
        nameWebsite: 'hentai24h', genreWebsite: "truyentranh18"},
    {linkComic: 'https://truyengihotqua.com/',
        nameWebsite: 'truyengihot', genreWebsite: "truyentranh18"},
    {linkComic: 'https://hentaivv1.com/',
        nameWebsite: 'hentaivv', genreWebsite: "truyentranh18"},
    // Danh sach website truyen tranh nuoc ngoai--------------------------
    
]
export {api, websiteComic}






